### ISSUE TITLE
API: пакетный sql_do_insert

### ISSUE THREAD

**Issue by jonny64** [do-/dia.pm#1]
а есть sql_do_bulk_insert ? быстрая массовая вставка массива записей одним запросом

**Comment by do-** [comment]
Пакетный вариант есть у [sql_do_upsert](https://github.com/do-/dia.pm/wiki/).

У sql_do_insert пока нет, добавлю по аналогии.

**Comment by jonny64** [comment]
Интересует именно (только) просто массовая вставка

Например в xtr блоке Задолженность в voc_agent_mosenergo_debt импорт из xls
sql_do_insert по 4k строк отрывается по таймауту в 10 секунд
Придумать синтетический уникальный ключ для sql_do_upsert - не понимаю как

в housing для таких целей (огромные импорты) есть _sql_do_bulk_insert_limit (table => $i)
 - при вызове в цикле он буферизирует вставляемую $i
 - при переполнении буфера (умолчание 10k записей) делает вставку одним запросом
 - последний вызов _sql_do_bulk_insert_limit (table) вне тела цикла очищает и вставляет остатки из буфера

**Comment by do-** [comment]
https://github.com/do-/dia.pm/commit/7a98f8f978a07da430714e1871e2012825977afb
